"""Core engine orchestrating concert data retrieval, track matching, and playlist creation."""

from dataclasses import dataclass

from touring_machine.exceptions import TouringMachineError
from touring_machine.matcher import MatchResult, TrackMatcher
from touring_machine.models import Artist, ConcertSetlist, Playlist, Track
from touring_machine.providers.base import ConcertDataProvider
from touring_machine.services.base import StreamingService
from touring_machine.strategies.factory import get_strategy


@dataclass
class GenerationResult:
    """Detailed summary of the playlist generation execution."""

    playlist: Playlist
    artist: Artist
    setlists: list[ConcertSetlist]
    matched_tracks: list[Track]
    unmatched_songs: list[str]
    match_results: list[MatchResult]


class PlaylistGenerator:
    """Coordinates concert data providers, strategies, matchers, and streaming services."""

    def __init__(
        self,
        streaming_service: StreamingService,
        concert_provider: ConcertDataProvider,
        matcher: TrackMatcher | None = None,
    ) -> None:
        self.service = streaming_service
        self.provider = concert_provider
        self.matcher = matcher or TrackMatcher(streaming_service)

    def generate(
        self,
        artist_name: str,
        shows: int = 5,
        limit: int | None = 25,
        strategy_name: str = "most-played",
        playlist_name: str | None = None,
        description: str | None = None,
    ) -> GenerationResult:
        """Fetch setlists, resolve tracks, create and populate playlist on streaming platform."""
        setlists = self.provider.get_recent_setlists(artist_name, limit=shows)
        if not setlists:
            msg = f"No recent concert setlists found for artist '{artist_name}'."
            raise TouringMachineError(msg)

        target_artist = setlists[0].artist

        # Generate target tracklist using selected strategy
        strategy = get_strategy(strategy_name)
        target_song_titles = strategy.generate_tracklist(setlists, limit=limit)
        if not target_song_titles:
            msg = f"No playable songs found in recent setlists for '{target_artist.name}'."
            raise TouringMachineError(msg)

        # Match songs against streaming service catalog
        match_results = self.matcher.match_songs(target_song_titles, target_artist.name)
        matched_tracks = [m.track for m in match_results if m.matched and m.track]
        unmatched_songs = [m.query_song for m in match_results if not m.matched]

        # Name and description defaults
        name = playlist_name or f"{target_artist.name} - Concert Setlist"
        desc = description or (
            f"{strategy.description} ({len(setlists)} shows analyzed). "
            f"Generated by Touring Machine."
        )

        # Create playlist
        playlist = self.service.create_playlist(name=name, description=desc)

        # Populate playlist with tracks
        if matched_tracks:
            self.service.add_tracks(playlist.id, matched_tracks)
            playlist.tracks = matched_tracks

        return GenerationResult(
            playlist=playlist,
            artist=target_artist,
            setlists=setlists,
            matched_tracks=matched_tracks,
            unmatched_songs=unmatched_songs,
            match_results=match_results,
        )
